Add CTest doc
launchableinc/cli pull request #126
Opened 2021-02-03 11:39 UTC by ninjinkun

https://github.com/launchableinc/cli/pull/125

2021-02-03 15:11 UTC, kohsuke requested changes
And finally, this is just a thought, but given the error-proneness in converting to JUnit, and if CTest already has its native XML format, to me it makes sense to just switch to parsing that format directly.

It saves the integration smoother by saving users one extra step, it makes CSM easier by eliminating this problem entirely, and in terms of the implementation effort, there's SAX-based parsing code that I created some time ago and, I'm hoping that can be reused quickly.

I'll leave it up to you to decide how best to proceed -- you know the best what are the other priorities and the effort you can spend on this one.

From my perspective, the only "show stopper" change is a broken `xsltproc` invocation.

2021-02-03 15:11 UTC, kohsuke commented on docs/integrations/ctest.md
> +CTest does not natively produce JUnit compatible test report files, so you should use an extra tool such as [`xsltproc`](http://xmlsoft.org/xslt/xsltproc.html) and [`ctest-to-junit`](https://github.c
As we all know, JUnit report files produced must contain key bits of information in the right way in order for the subset to work. Yet I notice that the documentation is somewhat open-ended about how to produce JUnit report files. Isn't that inviting a trouble, or did I miss something that makes this process actually more robust than I thought?

* A quick look at the referenced XSLT stylesheet shows test names are having their `-` replaecd to `_`. If we are matching with test names, that creates a problem, I'd think.
* Given the error prone nature of this process, I wouldn't use a phrase like "such as", which implies other tools are OK. Or perhaps be more specific about what this format needs to satisfy.

2021-02-03 15:11 UTC, kohsuke commented on docs/integrations/ctest.md
> +xsltproc ctest-to-junit.xsl Testing/**/Test.xml > Testing/**/junit.xml
Pretty sure `> Testing/**/junit.xml` doesn't work.

2021-02-04 02:46 UTC, ninjinkun commented
I agree to support CUnit's XML format. Instead of handle the XML format directory, I propose to use XSLT in the python code because we can continue to use `junitparser`:
```python
import lxml.etree as ET

dom = ET.parse(input)
xslt = ET.parse(xslt_file)
transform = ET.XSLT(xslt)
converted = transform(dom)
```

However, I notice that this XSLT feature requires `lxml` module depends on `libxml2`. Should we avoid `libxml2` dependency?

2021-02-04 13:50 UTC, ninjinkun commented
I fixed it to support CTest's XML!

2021-02-04 17:26 UTC, kohsuke approved these changes
Great to see that it's gotten better so quickly!

2021-02-05 07:35 UTC, merged