Add some validations
launchableinc/cli pull request #520
Opened 2022-12-13 08:08 UTC by Konboi

I realized some users faced some integration issues, so I edited that easy to notice the cause of issues.

## Changes

1. If subset candidates are empty and isn't set `--get-tests-from-previous-sessions` option, it's usually integration miss. So, I changed it to an error.
2. In the maven profile, when they set `--test-compile-created-file` and source_roots both, source_roots will be ignored so I updated to show the warning message.
3. Even if `--test-compile-created-file` is set but the file is empty, to show a warning message. 

## Others

Also, I fixed some minor changes

2022-12-13 09:46 UTC, Konboi commented on launchable/commands/subset.py
> +                    summary = res.json().get("summary", {})
There won’t be the such case that the summary is empty. But if the summary is empty and called by an old format, it will error. so I fixed this.

2022-12-13 19:40 UTC, draftcode requested changes

2022-12-13 19:40 UTC, draftcode commented on tests/commands/test_subset.py
> +            input=pipe,
I think so.

2022-12-13 19:40 UTC, draftcode commented on launchable/test_runners/pytest.py
> +    file, case, cls_name = None, None, None
Is this the appropriate behavior? With this, it's silently write a bogus name, right?

2022-12-14 01:27 UTC, Konboi commented on launchable/test_runners/pytest.py
> +    file, case, cls_name = None, None, None
Sorry, it's my misunderstood so I rebased this change.

2022-12-14 01:38 UTC, draftcode requested changes

2022-12-14 01:38 UTC, draftcode commented on launchable/commands/subset.py
> +            original_subset = []
I think we can revert this as well? Falling back to full run is orthogonal to this PR. (Also aligned with the comment above).

2022-12-14 02:13 UTC, shibuiwilliam approved these changes

2022-12-14 02:58 UTC, draftcode approved these changes

2022-12-14 04:10 UTC, merged