[ENG-474] new command to attach logs to a test session
launchableinc/cli pull request #627
Opened 2023-10-06 21:59 UTC by kohsuke

2023-10-06 22:00 UTC, kohsuke commented on launchable/commands/helper.py
> +    saved_build_name = require_build()
refactoring to use a newly introduced `require_build()`

2023-10-10 02:39 UTC, Konboi requested changes
Please fix CI
I'll review it again after fixing it.

2023-10-10 17:32 UTC, kohsuke commented
Oops, I didn't realize the rebase resulted in this much brokenness. My bad.

CI fixed up and it's ready for a review

2023-10-11 00:18 UTC, Konboi approved these changes

2023-10-11 22:30 UTC, merged